name: Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Release to Gradle plugin repository
        run: ./gradlew publishPlugins -Pgradle.publish.key="${PUBLISH_KEY}" -Pgradle.publish.secret="${PUBLISH_SECRET}";